config/routes.rb
Authority::Engine.routes.draw do
  resources :people do
    get 'viaf', on: :collection
  end

  resources :organizations do
    get 'viaf', on: :collection
  end

  get 'finder' => 'finder#search'
  get 'finder/search/:model/', to: 'finder#search'
  get 'finder/getobj/:id', to: 'finder#get_obj'
  get 'finder/searchbysameasuri/', to: 'finder#search_by_same_as_uri'
end

app/models/authority/Place.rb
module Authority
  class Place
    include ::Authority::Concern::Thing
    property :address, predicate: ::RDF::Vocab::SCHEMA.address, multiple: false
    property :geo, predicate: ::RDF::Vocab::SCHEMA.geo, multiple: false
  end
end

app/models/authority/auth_finder.rb
# This class should be called statically to execute common Solr queries
module Authority
  class AuthFinder

    def self.obj(id)
      ActiveFedora::SolrService.query("id:#{id}")
    end

    def self.all_things(q,model)
      q = q.downcase if q.present?
      q = q + "*"
      qs = q.split(" ") if q.present?
      qs ||= []
      qs.map!{|t| "typeahead_tesim:#{t}"}
      solr_q = qs.join(" && ")
      unless model == 'all'
        ActiveFedora::SolrService.query(solr_q,:fq=>"active_fedora_model_ssi:Authority*#{model}", :sort =>'display_value_ssi asc', :rows => self.max_rows)
      else
        ActiveFedora::SolrService.query(solr_q, :sort =>'display_value_ssi asc', :rows => self.max_rows)
      end
    end

    def self.model_query(model)
      "active_fedora_model_ssi: #{model}"
    end

    def self.max_rows
      1000000
    end
  end
end

app/models/authority/concern/thing.rb
module Authority
  module Concern
    module Thing
      extend ActiveSupport::Concern
      included do
        property :same_as, predicate: ::RDF::Vocab::SCHEMA.sameAs, multiple: true
        property :description, predicate: ::RDF::Vocab::SCHEMA.description, multiple: false
        property :image, predicate: ::RDF::Vocab::SCHEMA.image, multiple: false
        property :_name, predicate: ::RDF::Vocab::SCHEMA.name, multiple: false do |index|
          index.as :stored_searchable
        end
        property :alternate_names, predicate: ::RDF::Vocab::SCHEMA.alternateName, multiple: true


        #setters
        def same_as_uri=(uris)
          self.same_as = []
          uris.each do |uri|
            self.same_as += [::RDF::URI.new(uri)] if uri.present?
          end
        end

        def set_name=(full_name)
          self._name = full_name
        end

        #getters
        def same_as_uri
          result = []
          self.same_as.each do |s|
            result << s.to_term.value unless s.nil?
          end
          result
        end

        def date_range(dates={})
          date = ""
          date += "#{dates[:start_date]}-" if dates[:start_date].present?
          if dates[:end_date].present? then
            if dates[:start_date].present? then
              date += "#{dates[:end_date]}"
            else
              date += "-" + "#{dates[:end_date]}"
            end
          end
          date
        end

        def display_value
          value = ''
          value += _name if _name.present?
          if alternate_names.present? then
            value += ", "
            value += alternate_names.join(", ")
          end
          value
        end

        def to_solr(solr_doc = {})
          solr_doc.merge!(super)
          Solrizer.insert_field(solr_doc, 'display_value', display_value, :stored_searchable, :displayable)
          Solrizer.insert_field(solr_doc, 'display_value', display_value, :stored_sortable)
          Solrizer.insert_field(solr_doc, 'typeahead', display_value, :stored_searchable)
          Solrizer.insert_field(solr_doc, 'same_as_uri', same_as_uri, :stored_searchable)
          solr_doc
        end

        def self.find_or_create(search_params)
          results = self.where(search_params)
          if results.size > 0
            logger.warn "Multiple objects found with search_params #{search_params}" if results.size > 1
            results.first
          else
            self.create(search_params)
          end
        end
      end
    end
  end
end

app/models/authority/finder.rb
# This class should be called statically to execute common Solr queries
module Authority
  class Finder

    def self.obj(id)
      ActiveFedora::SolrService.query("id:#{id}")
    end

    def self.all_things(q,model)
      q = q.downcase if q.present?
      solr_q = "typeahead_tesim:#{q}* || typeahead_tesim:#{q}"
      unless model == 'all'
        ActiveFedora::SolrService.query(solr_q,:fq=>"active_fedora_model_ssi:Authority*#{model}", :sort =>'display_value_ssi asc')
      else
        ActiveFedora::SolrService.query(solr_q, :sort =>'display_value_ssi asc')
      end
    end

    def self.model_query(model)
      "active_fedora_model_ssi: #{model}"
    end

    def self.max_rows
      1000000
    end
  end
end

app/models/authority/organization.rb
module Authority
  class Organization < ::ActiveFedora::Base
    include Hydra::AccessControls::Permissions
    include ::Authority::Concern::Thing

    property :address, predicate: ::RDF::Vocab::SCHEMA.address, multiple: false
    property :contact_point, predicate: ::RDF::Vocab::SCHEMA.contactPoint, multiple: true
    property :department, predicate: ::RDF::Vocab::SCHEMA.department, multiple: false
    property :email, predicate: ::RDF::Vocab::SCHEMA.email, multiple: true do |index|
      index.as :stored_searchable
    end
    property :globbal_location_number, predicate: ::RDF::Vocab::SCHEMA.globalLocationNumber, multiple: false
    property :telephone, predicate: ::RDF::Vocab::SCHEMA.telephone, multiple: true
  end
end

app/models/authority/place.rb
module Authority
  class Place < ActiveFedora::Base
    include ::Authority::Concern::Thing
    property :address, predicate: ::RDF::Vocab::SCHEMA.address, multiple: false
    property :geo, predicate: ::RDF::Vocab::SCHEMA.geo, multiple: false
  end
end

app/controllers/authority/application_controller.rb
module Authority
  class ApplicationController < ActionController::Base
    layout 'application' # use the parent appliactions layout

    # simple methor to delegate missing path helper to the main app
    # a bit of a hack
    def method_missing method, *args, &block
      method.to_s.end_with?('_path', '_url') and main_app.respond_to?(method) ? main_app.send(method, *args) : super
    end

  end
end

app/controllers/authority/concerns/modal_layout.rb
module Authority
  module Concerns
    module ModalLayout
      extend ActiveSupport::Concern
      included do

        private

        def set_layout
          logger.debug("setting layout #{self.class}")
          self.class.layout = 'modal' if params['modal'].present?
        end
      end
    end
  end
end

app/controllers/authority/finder_controller.rb
require_dependency "authority/application_controller"

module Authority
  class FinderController < ApplicationController
    def search
      result = map_result(AuthFinder.all_things(params[:term],params[:model]))
      render json:  result
    end

    def get_obj
      result = map_result(AuthFinder.obj(URI.unescape(params[:id])))
      if result.empty?
        render :nothing => true, :status => '404'
      else
        render json: result[0]
      end
    end

    def search_by_same_as_uri
      result = map_result(AuthFinder.search_by_same_as_uri(params[:uri]))
      if result.empty?
        render :nothing => true, :status => '404'
      else
        render json: result[0]
      end
    end

    private

    def map_result(result)
      result = result.map {|doc| { :value => doc['display_value_ssm'].try(:first),:id => doc['id']} }
    end
  end
end

app/controllers/authority/organization_controller.rb
require_dependency "authority/application_controller"

module Authority
  class OrganizationController < ApplicationController

        before_action :set_organization, only: [:show, :edit, :update, :destroy]

        def index
          @org = Authority::Organization.all
        end

        def show
        end

        def edit
        end

        def update
          respond_to do |format|
            if @organization.update(organization_params)
              format.html { redirect_to @organization }
            else
              format.html { render :new }
            end
          end
        end

        def new
          @organization = Organization.new
        end

        def create
          @organization = Organization.new(organization_params)

          respond_to do |format|
            if @organization.save
              format.html { redirect_to @organization }
            else
              format.html { render :new }
            end
          end
        end

        def destroy
          @organization.destroy
          respond_to do |format|
            format.html { redirect_to organization_url }
          end
        end

        private

        def set_organization
          @organization = ActiveFedora::Base.where(id: URI.unescape(params[:id])).first
        end

  end
end

app/controllers/authority/organizations_controller.rb
require_dependency "authority/application_controller"

module Authority
  class OrganizationsController < ApplicationController
        authorize_resource
        before_filter do
          if params['modal'].present?
            self.class.layout  'modal' if params['modal'].present?
            logger.debug("modal is present ")
          else
            self.class.layout  'application'
          end
        end
       before_action :set_layout, only: [:show]
       before_action :set_organization, only: [:show, :edit, :update, :destroy]

        def index
          @organizations = Authority::Organization.all
        end

        def show
        end

        def edit
        end

        def update
          respond_to do |format|
            if @organization.update(person_params)
              format.html { redirect_to @organization }
            else
              format.html { render :new }
            end
          end
        end

        def new
          @organization = Organization.new
        end

        def create
          @organization = Organization.new(organization_params)

          respond_to do |format|
            if @organization.save
              format.html { redirect_to @organization }
              format.json  {render json: {id: @organization.id, name: @organization._name.force_encoding("UTF-8") } }
            else
              format.html { render :new }
              format.json { render json: @organization.errors, status: :unprocessable_entity }
            end
          end
        end

        def destroy
          @organization.destroy
          respond_to do |format|
            format.html { redirect_to organizations_url }
          end
        end

        def viaf
          reader = RDF::Reader.open(params[:url])
          stats = reader.each_statement.to_a

          unless stats.select {|s| s.predicate == 'http://schema.org/name' }.empty?
            org_name = stats.select {|s| s.predicate == 'http://schema.org/name' }.first.object.value
          end
          unless stats.select { |s| s.predicate == 'http://schema.org/alternateName' }.empty?
            alternate_name = stats.select { |s| s.predicate == 'http://schema.org/alternateName' }.first.object.value
          end
          unless stats.map {|s| s if s.predicate == 'http://schema.org/sameAs' and s.object.value.include? 'http://isni.org/isni/'}.all? &:nil?
          isni_uri = stats.map {|s| s if s.predicate == 'http://schema.org/sameAs' and
              s.object.value.include? 'http://isni.org/isni/'}.compact.first.object.value
          end

          json_file = {:org_name => org_name, :alternate_name => alternate_name, :isni_uri => isni_uri}
          render json: json_file.to_json
        end

        private

        def set_organization
          @organization = ActiveFedora::Base.where(id: URI.unescape(params[:id])).first
        end

        def organization_params
          params.require(:organization).permit( :_name, :description, :department,
          :address, :globbal_location_number, alternate_names: [],
          email: [], contact_point: [], telephone: [])
        end

  end
end

app/controllers/authority/people_controller.rb
require_dependency "authority/application_controller"

module Authority
   include Authority::Concerns::ModalLayout

   class PeopleController < ApplicationController
     authorize_resource
     before_filter do
       if params['modal'].present?
          self.class.layout  'modal' if params['modal'].present?
          logger.debug("modal is present ")
       else
         self.class.layout  'application'
       end
     end
     before_action :set_person, only: [:show, :edit, :update, :destroy]

     def index
       @people = Authority::Person.all
     end

     def show
     end

     def edit
     end

     def update
       respond_to do |format|
         if @person.update(person_params)
           format.html { redirect_to @person }
         else
           format.html { render :new }
         end
       end
     end

     def new
       @person = Person.new
     end

     def create
       @person = Person.new(person_params)

       respond_to do |format|
         if @person.save
           format.html { redirect_to @person }
           format.json  {render json: {id: @person.id, name: @person._name.force_encoding("UTF-8") } }
         else
           format.html { render :new }
           format.json { render json: @person.errors, status: :unprocessable_entity }
         end
       end
     end

     def destroy
       @person.destroy
       respond_to do |format|
         format.html { redirect_to people_url }
       end
     end

     def viaf
       reader = RDF::Reader.open(params[:url])
       stats = reader.each_statement.to_a

       unless stats.select { |s| s.predicate == 'http://schema.org/givenName' }.empty?
         first_name = stats.select { |s| s.predicate == 'http://schema.org/givenName' }.first.object.value
       end
       unless stats.select { |s| s if s.predicate == 'http://schema.org/familyName' }.empty?
         family_name = stats.select { |s| s if s.predicate == 'http://schema.org/familyName' }.first.object.value
       end
       unless stats.select { |s| s.predicate == 'http://schema.org/alternateName' }.empty?
         alternate_name = stats.select { |s| s.predicate == 'http://schema.org/alternateName' }.first.object.value
       end
       unless stats.map { |s| s if s.predicate == 'http://schema.org/sameAs' and s.object.value.include? 'http://isni.org/isni/' }.all? &:nil?
         isni_uri = stats.map { |s| s if s.predicate == 'http://schema.org/sameAs' and
             s.object.value.include? 'http://isni.org/isni/' }.compact.first.object.value
       end

       json_file = {:first_name => first_name, :family_name => family_name, :alternate_name => alternate_name,
                    :isni_uri => isni_uri}
       render json: json_file.to_json
     end

     private

     def set_person
       @person = ActiveFedora::Base.where(id: URI.unescape(params[:id])).first
     end

     def person_params
       params.require(:person).permit( :_name, :description,
                                       :given_name, :family_name, :additional_name,
                                       :award,
                                       :birth_date, :death_date,
                                       :address, :gender, :job_title, :honorific_prefix, :honorific_suffix,
                                       email: [], same_as_uri:[], alternate_names: [])
     end
   end
end

app/helpers/authority/application_helper.rb
module Authority
  module ApplicationHelper
  end
end

app/views/authority/people/_form.html.erb
<%= form_for(@person) do |f| %>
    <%= render partial: 'authority/things/thing_fields', locals: {f: f, thing: @person} %>
    <%= render partial: 'person_fields', locals: {f: f, person: :person} %>
    <%= f.submit 'Gem person'  unless params['modal'].present? %>
<% end %>

app/views/authority/people/_person_fields.html.erb
<!--<h3>Personal details</h3>-->


<table class="table table-striped">
  <tbody>

  <tr>
    <td>
      <strong><%= label person, :given_name, 'Given name:' %></strong>
    </td>
    <td>
      <%= text_field person, :given_name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%= label person, :family_name, 'Family name:' %></strong>
    </td>
    <td>
      <%= text_field person, :family_name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%= label person, :additional_name, 'Additional name:' %></strong>
    </td>
    <td>
      <%= text_field person, :additional_name %>
    </td>
  </tr>
  <!--<tr>
    <td>
      <strong><%#= label person, :award, 'Award:' %></strong>
    </td>
    <td>
      <%#= text_field person, :award %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%#= label person, :address, 'Address:' %></strong>
    </td>
    <td>
      <%#= text_field person, :address %>
    </td>
  </tr>-->
  <tr>
    <td>
      <strong><%= label person, :gender, 'Gender:' %></strong>
    </td>
    <td>
      <%= text_field person, :gender %>
    </td>
  </tr>
  <!--<tr>
    <td>
      <strong><%#= label person, :job_title, 'Job title:' %></strong>
    </td>
    <td>
      <%#= text_field person, :job_title %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%#= label person, :email, 'Email:' %></strong>
    </td>
    <td>
      <%# if !@person.email.empty? %>
          <%# @person.email.each do |email| %>
              <%#= text_field person, :email, :multiple => true, :value => email %>
          <%# end %>
      <%# else %>
          <%#= text_field person, :email, :multiple => true %>
      <%# end %>
      <%#= button_tag "Add more", type: 'button', data: {function: 'clone-input'} %>
    </td>
  </tr>-->
  <tr>
    <td>
      <strong><%= label person, :birth_date, 'Birth date:' %></strong>
    </td>
    <td>
      <%= text_field person, :birth_date %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%= label person, :death_date, 'Death date:' %></strong>
    </td>
    <td>
      <%= text_field person, :death_date %>
    </td>
  </tr>
  <!--<tr>
    <td>
      <strong><%#= label person, :honorific_prefix, 'Honorific prefix:' %></strong>
    </td>
    <td>
      <%#= text_field person, :honorific_prefix %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%#= label person, :honorific_suffix, 'Honorific suffix:' %></strong>
    </td>
    <td>
      <%#= text_field person, :honorific_suffix %>
    </td>
  </tr>-->

  </tbody>
</table>

app/views/authority/people/_show_person.html.erb
<h3>Personal details</h3>
<table class="table table-striped">
  <tbody>
  <% unless person.given_name.blank? %>
      <tr>
        <td>
          <strong>Given name:</strong>
        </td>
        <td>
          <span><%= person.given_name %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.family_name.blank? %>
      <tr>
        <td>
          <strong>Family name:</strong>
        </td>
        <td>
          <span><%= person.family_name %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.additional_name.blank? %>
      <tr>
        <td>
          <strong>Additional name:</strong>
        </td>
        <td>
          <span><%= person.additional_name %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.award.blank? %>
      <tr>
        <td>
          <strong>Award:</strong>
        </td>
        <td>
          <span><%= person.award %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.address.blank? %>
      <tr>
        <td>
          <strong>Address:</strong>
        </td>
        <td>
          <span><%= person.address %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.gender.blank? %>
      <tr>
        <td>
          <strong>Gender:</strong>
        </td>
        <td>
          <span><%= person.gender %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.job_title.blank? %>
      <tr>
        <td>
          <strong>Job title:</strong>
        </td>
        <td>
          <span><%= person.job_title %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.email.blank? %>
      <tr>
        <td>
          <strong>Email address:</strong>
        </td>
        <td>
          <span><%= @person.email.join(", ") %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.birth_date.blank? %>
      <tr>
        <td>
          <strong>Birth date:</strong>
        </td>
        <td>
          <span><%= person.birth_date %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.death_date.blank? %>
      <tr>
        <td>
          <strong>Death date:</strong>
        </td>
        <td>
          <span><%= person.death_date %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.honorific_prefix.blank? %>
      <tr>
        <td>
          <strong>Honorific prefix:</strong>
        </td>
        <td>
          <span><%= person.honorific_prefix %></span>
        </td>
      </tr>
  <% end %>
  <% unless person.honorific_suffix.blank? %>
      <tr>
        <td>
          <strong>Honorific suffix:</strong>
        </td>
        <td>
          <span><%= person.honorific_suffix %></span>
        </td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/authority/people/_thing_fields.html.erb
<h3>General</h3>
<table class="table table-striped">
  <tbody>
  <tr>
    <td>
      <strong><%= label thing, :_name, 'Name:' %></strong>
    </td>
    <td>
      <%= text_field thing, :_name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%= label thing, :alternate_names, 'Alternate Names:' %></strong>
    </td>
    <td>
      <% if !@organization.alternate_names.empty? %>
          <% @organization.alternate_names.each do |alternateN| %>
              <%= text_field organization, :alternate_names, :multiple => true, :value => alternateN %>
          <% end %>
      <% else %>
          <%= text_field thing, :alternate_names, :multiple => true %>
      <% end %>
      <%= button_tag "Add more", type: 'button', data: {function: 'clone-input'} %>
    </td>
  </tr>
  <tr>
    <td>
      <strong><%= label thing, :description, 'Description:' %></strong>
    </td>
    <td>
      <%= text_field thing, :description %>
    </td>
  </tr>
  </tbody>
</table>

app/views/authority/people/edit.html.erb
<h1>Edit Person <%= @person.display_value %></h1>

<%= render 'form' %>

<%= link_to 'show', @person %> |
<%= link_to 'back', person_path %>

app/views/authority/people/index.html.erb
<h1><%= t('.list', var: @klazz.to_s) %></h1>

<table class="table">
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.display_value, person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Delete', person_path(person), method: :delete, data: { confirm: 'Confirm'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/authority/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'back', people_url unless params['modal'].present? %>

app/views/authority/people/show.html.erb
<% @page_title="Person: " + @person.display_value  %>

<div class="container">
  <h1><%= @person.display_value %></h1>

  <%= render partial: 'authority/things/show_thing', locals: {thing: @person} %>
  <%= render partial: 'show_person', locals: {person: @person} %>

  <%= link_to 'Edit', edit_person_path(@person) %>

</div>

app/views/authority/people/show.xml.erb
<%= @person.as_json.merge({"type"=>"person"}).to_xml(:root => 'authority').html_safe %>